name: Test Release Build & Distribute

on:
  push:
    branches:
      - test-release
  pull_request:
    branches:
      - test-release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install -g eas-cli firebase-tools && npm install

      - name: Authenticate Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase.json

      - name: Build Android App with EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --profile test-release --platform android --non-interactive

      - name: Wait for Build to Complete & Download APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          BUILD_ID=$(eas build:list --json | jq -r '.[0].id')
          echo "Waiting for build to complete..."
          eas build:wait --build-id $BUILD_ID
          BUILD_URL=$(eas build:list --json | jq -r '.[0].artifacts.buildUrl')
          echo "Downloading APK from $BUILD_URL"
          curl -o app.apk "$BUILD_URL"

      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute app.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --groups testers
